version: '3.7' # specify docker-compose version (docker -v)

services: 

  api-r:
    build: DataMining # directory of the dockerfile
    image: escobarana/tfg-app:plumber # specify image to build container from
    ports:
      - '7190:7190'    # specify port mapping

  #client:
  #  hostname: 156.35.163.172
  #  build: client # directory of the dockerfile
  #  image: escobarana/tfg-app:client # specify image to build container from
  #  ports:
  #    - "8181:80" # specify port forewarding

  server:
    build: . # directory of the dockerfile
    image: escobarana/tfg-app:server # specify image to build container from
    ports:
      - '80:3000'    # specify port mapping    

