version: '3.7' # specify docker-compose version (docker -v)

services: 

  api-r:
    build: DataMining                 # directory of the dockerfile
    image: escobarana/tfg-app:plumber # specify image to build container from
    ports:
      - '7190:7190'                   # specify port mapping

  server:
    build: .                          # directory of the dockerfile
    image: escobarana/tfg-app:server  # specify image to build container from
    ports:
      #- '80:80'                       # specify port mapping
      #- '443:3000'                    # specify port mapping  
      - '80:3000'
