version: '3.7' # specify docker-compose version (docker -v)

services: 

#  mongo-db:
#    image: mongo
#    ports: 
#      - '27017:27017'

  api-r:
    build: DataMining # directory of the dockerfile
    image: escobarana/plumber # specify image to build container from
    ports:
      - '7190:7190'    # specify port mapping

  server:
    build: . # directory of the dockerfile
    image: escobarana/server # specify image to build container from
    ports:
      - '3000:3000'    # specify port mapping
    links:
      - api-r
#      - mongo-db    

  client:
    build: client # directory of the dockerfile
    image: escobarana/client # specify image to build container from
    ports:
      - '4200:4200'    # specify port mapping

