version: '3.7' # specify docker-compose version (docker -v)

services: 

  api-r:
    build: DataMining # directory of the dockerfile
    image: escobarana/tfg-app:plumber # specify image to build container from
    ports:
      - '7190:7190'    # specify port mapping

  client:
    build: client # directory of the dockerfile
    image: escobarana/tfg-app:client # specify image to build container from
    ports:
      - '4200:4200'    # specify port mapping

  server:
    build: . # directory of the dockerfile
    image: escobarana/tfg-app:server # specify image to build container from
    ports:
      - '3000:3000'    # specify port mapping    

